ALTER TABLE B_TERRAFORM_IF_INFO ADD COLUMN TERRAFORM_PROXY_ADDRESS VARCHAR(128) AFTER TERRAFORM_TOKEN;
ALTER TABLE B_TERRAFORM_IF_INFO_JNL ADD COLUMN TERRAFORM_PROXY_ADDRESS VARCHAR(128) AFTER TERRAFORM_TOKEN;

ALTER TABLE B_TERRAFORM_IF_INFO ADD COLUMN TERRAFORM_PROXY_PORT INT AFTER TERRAFORM_PROXY_ADDRESS;
ALTER TABLE B_TERRAFORM_IF_INFO_JNL ADD COLUMN TERRAFORM_PROXY_PORT INT AFTER TERRAFORM_PROXY_ADDRESS;

CREATE OR REPLACE VIEW D_TERRAFORM_IF_INFO AS 
SELECT * 
FROM B_TERRAFORM_IF_INFO;

CREATE OR REPLACE VIEW D_TERRAFORM_IF_INFO_JNL AS 
SELECT * 
FROM B_TERRAFORM_IF_INFO_JNL;


ALTER TABLE C_TERRAFORM_EXE_INS_MNG ADD COLUMN I_TERRAFORM_ORGANIZATION_WORKSPACE VARCHAR(256) AFTER I_TERRAFORM_WORKSPACE_ID;
ALTER TABLE C_TERRAFORM_EXE_INS_MNG_JNL ADD COLUMN I_TERRAFORM_ORGANIZATION_WORKSPACE VARCHAR(256) AFTER I_TERRAFORM_WORKSPACE_ID;


CREATE OR REPLACE VIEW E_TERRAFORM_EXE_INS_MNG AS
SELECT 
         TAB_A.EXECUTION_NO              ,
         TAB_A.STATUS_ID                 ,
         TAB_C.STATUS_NAME               ,
         TAB_A.SYMPHONY_NAME             ,
         TAB_A.EXECUTION_USER            ,
         TAB_A.SYMPHONY_INSTANCE_NO      , -- Symphonyインスタンス番号
         TAB_A.PATTERN_ID                ,
         TAB_A.I_PATTERN_NAME            ,
         TAB_A.I_TIME_LIMIT              ,
         TAB_A.I_TERRAFORM_RUN_ID        ,
         TAB_A.I_TERRAFORM_WORKSPACE_ID  ,
         TAB_A.I_TERRAFORM_ORGANIZATION_WORKSPACE,
         TAB_A.OPERATION_NO_UAPK         ,
         TAB_A.I_OPERATION_NAME          ,
         TAB_A.I_OPERATION_NO_IDBH       ,
         TAB_A.CONDUCTOR_NAME            ,
         TAB_A.CONDUCTOR_INSTANCE_NO     ,
         TAB_A.TIME_BOOK                 ,
         TAB_A.TIME_START                ,
         TAB_A.TIME_END                  ,
         TAB_A.FILE_INPUT                ,
         TAB_A.FILE_RESULT               ,
         TAB_A.RUN_MODE                  ,
         TAB_D.RUN_MODE_NAME             ,
         TAB_A.DISP_SEQ                  ,
         TAB_A.ACCESS_AUTH               ,
         TAB_A.NOTE                      ,
         TAB_A.DISUSE_FLAG               ,
         TAB_A.LAST_UPDATE_TIMESTAMP     ,
         TAB_A.LAST_UPDATE_USER
FROM C_TERRAFORM_EXE_INS_MNG       TAB_A
LEFT JOIN E_TERRAFORM_PATTERN      TAB_B ON ( TAB_B.PATTERN_ID = TAB_A.PATTERN_ID )
LEFT JOIN D_TERRAFORM_INS_STATUS   TAB_C ON ( TAB_A.STATUS_ID = TAB_C.STATUS_ID )
LEFT JOIN D_TERRAFORM_INS_RUN_MODE TAB_D ON ( TAB_A.RUN_MODE = TAB_D.RUN_MODE_ID )
;

CREATE OR REPLACE VIEW E_TERRAFORM_EXE_INS_MNG_JNL AS 
SELECT 
         TAB_A.JOURNAL_SEQ_NO            ,
         TAB_A.JOURNAL_REG_DATETIME      ,
         TAB_A.JOURNAL_ACTION_CLASS      ,
         TAB_A.EXECUTION_NO              ,
         TAB_A.STATUS_ID                 ,
         TAB_C.STATUS_NAME               ,
         TAB_A.SYMPHONY_NAME             ,
         TAB_A.EXECUTION_USER            ,
         TAB_A.SYMPHONY_INSTANCE_NO      , -- Symphonyインスタンス番号
         TAB_A.PATTERN_ID                ,
         TAB_A.I_PATTERN_NAME            ,
         TAB_A.I_TIME_LIMIT              ,
         TAB_A.I_TERRAFORM_RUN_ID        ,
         TAB_A.I_TERRAFORM_WORKSPACE_ID  ,
         TAB_A.I_TERRAFORM_ORGANIZATION_WORKSPACE,
         TAB_A.OPERATION_NO_UAPK         ,
         TAB_A.I_OPERATION_NAME          ,
         TAB_A.I_OPERATION_NO_IDBH       ,
         TAB_A.CONDUCTOR_NAME            ,
         TAB_A.CONDUCTOR_INSTANCE_NO     ,
         TAB_A.TIME_BOOK                 ,
         TAB_A.TIME_START                ,
         TAB_A.TIME_END                  ,
         TAB_A.FILE_INPUT                ,
         TAB_A.FILE_RESULT               ,
         TAB_A.RUN_MODE                  ,
         TAB_D.RUN_MODE_NAME             ,
         TAB_A.DISP_SEQ                  ,
         TAB_A.ACCESS_AUTH               ,
         TAB_A.NOTE                      ,
         TAB_A.DISUSE_FLAG               ,
         TAB_A.LAST_UPDATE_TIMESTAMP     ,
         TAB_A.LAST_UPDATE_USER           
FROM C_TERRAFORM_EXE_INS_MNG_JNL   TAB_A
LEFT JOIN E_TERRAFORM_PATTERN      TAB_B ON ( TAB_B.PATTERN_ID = TAB_A.PATTERN_ID )
LEFT JOIN D_TERRAFORM_INS_STATUS   TAB_C ON ( TAB_A.STATUS_ID = TAB_C.STATUS_ID )
LEFT JOIN D_TERRAFORM_INS_RUN_MODE TAB_D ON ( TAB_A.RUN_MODE = TAB_D.RUN_MODE_ID )
;


UPDATE A_MENU_LIST SET NOTE='' WHERE MENU_ID IN (2100080001,2100080002,2100080003,2100080004,2100080005,2100080006,2100080008,2100080009,2100080010,2100080011,2100080012,2100080013,2100080014,2100080015,2100080016);
UPDATE A_MENU_LIST_JNL SET NOTE='' WHERE MENU_ID IN (2100080001,2100080002,2100080003,2100080004,2100080005,2100080006,2100080007,2100080008,2100080009,2100080010,2100080011,2100080012,2100080013,2100080014,2100080015,2100080016);

UPDATE A_MENU_LIST SET MENU_NAME='Movement module link', NOTE='' WHERE MENU_ID IN (2100080007);
UPDATE A_MENU_LIST_JNL SET MENU_NAME='Movement module link', NOTE='' WHERE MENU_ID IN (2100080007);

UPDATE A_MENU_LIST SET MENU_NAME='Linked Terraform management', NOTE='' WHERE MENU_ID IN (2100080017);
UPDATE A_MENU_LIST_JNL SET MENU_NAME='Linked Terraform management', NOTE='' WHERE MENU_ID IN (2100080017);
