ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN TYPE3_REFERENCE INT AFTER REFERENCE_ITEM;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN SINGLE_DEFAULT_VALUE TEXT AFTER TYPE3_REFERENCE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN MULTI_DEFAULT_VALUE TEXT AFTER SINGLE_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN INT_DEFAULT_VALUE INT AFTER MULTI_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN FLOAT_DEFAULT_VALUE DOUBLE AFTER INT_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN DATETIME_DEFAULT_VALUE DATETIME(6) AFTER FLOAT_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN DATE_DEFAULT_VALUE DATETIME(6) AFTER DATETIME_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN PULLDOWN_DEFAULT_VALUE INT AFTER DATE_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN LINK_DEFAULT_VALUE TEXT AFTER PULLDOWN_DEFAULT_VALUE;

ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN TYPE3_REFERENCE INT AFTER REFERENCE_ITEM;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN SINGLE_DEFAULT_VALUE TEXT AFTER TYPE3_REFERENCE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN MULTI_DEFAULT_VALUE TEXT AFTER SINGLE_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN INT_DEFAULT_VALUE INT AFTER MULTI_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN FLOAT_DEFAULT_VALUE DOUBLE AFTER INT_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN DATETIME_DEFAULT_VALUE DATETIME(6) AFTER FLOAT_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN DATE_DEFAULT_VALUE DATETIME(6) AFTER DATETIME_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN PULLDOWN_DEFAULT_VALUE INT AFTER DATE_DEFAULT_VALUE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN LINK_DEFAULT_VALUE TEXT AFTER PULLDOWN_DEFAULT_VALUE;


CREATE OR REPLACE VIEW G_CREATE_ITEM_INFO AS 
SELECT TAB_A.CREATE_ITEM_ID,
       TAB_A.CREATE_MENU_ID,
       TAB_A.ITEM_NAME,
       TAB_A.DISP_SEQ,
       TAB_A.REQUIRED,
       TAB_A.UNIQUED,
       TAB_A.COL_GROUP_ID,
       TAB_A.INPUT_METHOD_ID,
       TAB_A.MAX_LENGTH,
       TAB_A.MULTI_MAX_LENGTH,
       TAB_A.PREG_MATCH,
       TAB_A.MULTI_PREG_MATCH,
       TAB_A.OTHER_MENU_LINK_ID,
       TAB_A.INT_MAX,
       TAB_A.INT_MIN,
       TAB_A.FLOAT_MAX,
       TAB_A.FLOAT_MIN,
       TAB_A.FLOAT_DIGIT,
       TAB_A.PW_MAX_LENGTH,
       TAB_A.UPLOAD_MAX_SIZE,
       TAB_A.LINK_LENGTH,
       TAB_A.REFERENCE_ITEM,
       TAB_A.TYPE3_REFERENCE,
       TAB_A.SINGLE_DEFAULT_VALUE,
       TAB_A.MULTI_DEFAULT_VALUE,
       TAB_A.INT_DEFAULT_VALUE,
       TAB_A.FLOAT_DEFAULT_VALUE,
       TAB_A.DATETIME_DEFAULT_VALUE,
       TAB_A.DATE_DEFAULT_VALUE,
       TAB_A.PULLDOWN_DEFAULT_VALUE,
       TAB_A.LINK_DEFAULT_VALUE,
       TAB_A.DESCRIPTION,
       TAB_C.FULL_COL_GROUP_NAME,
       CASE
           WHEN TAB_C.FULL_COL_GROUP_NAME IS NULL THEN CONCAT(TAB_B.MENU_NAME,':',TAB_A.ITEM_NAME)
           ELSE CONCAT(TAB_B.MENU_NAME,':',TAB_C.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME)
       END LINK_PULLDOWN,
       TAB_A.ACCESS_AUTH,
       TAB_A.NOTE,
       TAB_A.DISUSE_FLAG,
       TAB_A.LAST_UPDATE_TIMESTAMP,
       TAB_A.LAST_UPDATE_USER,
       TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01,
       TAB_C.ACCESS_AUTH AS ACCESS_AUTH_02
FROM F_CREATE_ITEM_INFO TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID)
LEFT JOIN F_COLUMN_GROUP TAB_C ON (TAB_A.COL_GROUP_ID = TAB_C.COL_GROUP_ID)
WHERE TAB_B.VERTICAL != ""
;


CREATE OR REPLACE VIEW G_CREATE_ITEM_INFO_JNL AS 
SELECT TAB_A.JOURNAL_SEQ_NO,
       TAB_A.JOURNAL_REG_DATETIME,
       TAB_A.JOURNAL_ACTION_CLASS,
       TAB_A.CREATE_ITEM_ID,
       TAB_A.CREATE_MENU_ID,
       TAB_A.ITEM_NAME,
       TAB_A.DISP_SEQ,
       TAB_A.REQUIRED,
       TAB_A.UNIQUED,
       TAB_A.COL_GROUP_ID,
       TAB_A.INPUT_METHOD_ID,
       TAB_A.MAX_LENGTH,
       TAB_A.MULTI_MAX_LENGTH,
       TAB_A.PREG_MATCH,
       TAB_A.MULTI_PREG_MATCH,
       TAB_A.OTHER_MENU_LINK_ID,
       TAB_A.INT_MAX,
       TAB_A.INT_MIN,
       TAB_A.FLOAT_MAX,
       TAB_A.FLOAT_MIN,
       TAB_A.FLOAT_DIGIT,
       TAB_A.PW_MAX_LENGTH,
       TAB_A.UPLOAD_MAX_SIZE,
       TAB_A.LINK_LENGTH,
       TAB_A.REFERENCE_ITEM,
       TAB_A.TYPE3_REFERENCE,
       TAB_A.SINGLE_DEFAULT_VALUE,
       TAB_A.MULTI_DEFAULT_VALUE,
       TAB_A.INT_DEFAULT_VALUE,
       TAB_A.FLOAT_DEFAULT_VALUE,
       TAB_A.DATETIME_DEFAULT_VALUE,
       TAB_A.DATE_DEFAULT_VALUE,
       TAB_A.PULLDOWN_DEFAULT_VALUE,
       TAB_A.LINK_DEFAULT_VALUE,
       TAB_A.DESCRIPTION,
       CASE
           WHEN TAB_C.FULL_COL_GROUP_NAME IS NULL THEN CONCAT(TAB_B.MENU_NAME,':',TAB_A.ITEM_NAME)
           ELSE CONCAT(TAB_B.MENU_NAME,':',TAB_C.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME)
       END LINK_PULLDOWN,
       TAB_A.ACCESS_AUTH,
       TAB_A.NOTE,
       TAB_A.DISUSE_FLAG,
       TAB_A.LAST_UPDATE_TIMESTAMP,
       TAB_A.LAST_UPDATE_USER,
       TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01,
       TAB_C.ACCESS_AUTH AS ACCESS_AUTH_02
FROM F_CREATE_ITEM_INFO_JNL TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID)
LEFT JOIN F_COLUMN_GROUP TAB_C ON (TAB_A.COL_GROUP_ID = TAB_C.COL_GROUP_ID)
WHERE TAB_B.VERTICAL != ""
;


CREATE OR REPLACE VIEW G_CREATE_REFERENCE_ITEM AS 
SELECT DISTINCT TAB_A.CREATE_ITEM_ID ITEM_ID      ,
       NULL AS LINK_ID                            ,
       TAB_C.MENU_ID MENU_ID                      ,
       TAB_A.DISP_SEQ DISP_SEQ                    ,
       TAB_C.TABLE_NAME TABLE_NAME                ,
       TAB_C.PRI_NAME PRI_NAME                    ,
       CASE WHEN CHAR_LENGTH(TAB_A.CREATE_ITEM_ID) <= 4 THEN CONCAT('KY_AUTO_COL_', lpad(TAB_A.CREATE_ITEM_ID, 4, '0')) ELSE CONCAT('KY_AUTO_COL_', TAB_A.CREATE_ITEM_ID) END AS COLUMN_NAME,
       TAB_A.ITEM_NAME ITEM_NAME                  ,
       TAB_D.FULL_COL_GROUP_NAME COL_GROUP_NAME   ,
       TAB_A.DESCRIPTION DESCRIPTION              ,
       TAB_A.INPUT_METHOD_ID INPUT_METHOD_ID      ,
       CASE WHEN TAB_A.INPUT_METHOD_ID = 8 THEN 2 ELSE 1 END AS SENSITIVE_FLAG,
       NULL AS ORIGINAL_MENU_FLAG                 ,
       TAB_A.ACCESS_AUTH                          ,
       TAB_A.NOTE                                 ,
       TAB_A.DISUSE_FLAG                          ,
       TAB_A.LAST_UPDATE_TIMESTAMP                ,
       TAB_A.LAST_UPDATE_USER                     ,
       TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01        ,
       TAB_C.ACCESS_AUTH AS ACCESS_AUTH_02        ,
       TAB_D.ACCESS_AUTH AS ACCESS_AUTH_03 
FROM F_CREATE_ITEM_INFO TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID)
LEFT JOIN G_OTHER_MENU_LINK TAB_C ON (TAB_B.MENU_NAME = TAB_C.MENU_NAME)
LEFT JOIN F_COLUMN_GROUP TAB_D ON (TAB_A.COL_GROUP_ID = TAB_D.COL_GROUP_ID)
WHERE NOT TAB_A.INPUT_METHOD_ID = 7 AND NOT TAB_A.INPUT_METHOD_ID = 11 AND TAB_B.DISUSE_FLAG='0' AND TAB_C.DISUSE_FLAG='0'
;


CREATE OR REPLACE VIEW G_CREATE_REFERENCE_ITEM_JNL AS 
SELECT DISTINCT TAB_A.JOURNAL_SEQ_NO              ,
       TAB_A.JOURNAL_REG_DATETIME                 ,
       TAB_A.JOURNAL_ACTION_CLASS                 ,
       TAB_A.CREATE_ITEM_ID ITEM_ID               ,
       NULL AS LINK_ID                            ,
       TAB_C.MENU_ID MENU_ID                      ,
       TAB_A.DISP_SEQ DISP_SEQ                    ,
       TAB_C.TABLE_NAME TABLE_NAME                ,
       TAB_C.PRI_NAME PRI_NAME                    ,
       CASE WHEN CHAR_LENGTH(TAB_A.CREATE_ITEM_ID) <= 4 THEN CONCAT('KY_AUTO_COL_', lpad(TAB_A.CREATE_ITEM_ID, 4, '0')) ELSE CONCAT('KY_AUTO_COL_', TAB_A.CREATE_ITEM_ID) END AS COLUMN_NAME,
       TAB_A.ITEM_NAME ITEM_NAME                  ,
       TAB_D.FULL_COL_GROUP_NAME COL_GROUP_NAME   ,
       TAB_A.DESCRIPTION DESCRIPTION              ,
       TAB_A.INPUT_METHOD_ID INPUT_METHOD_ID      ,
       CASE WHEN TAB_A.INPUT_METHOD_ID = 8 THEN 2 ELSE 1 END AS SENSITIVE_FLAG,
       NULL AS ORIGINAL_MENU_FLAG                 ,
       TAB_A.ACCESS_AUTH                          ,
       TAB_A.NOTE                                 ,
       TAB_A.DISUSE_FLAG                          ,
       TAB_A.LAST_UPDATE_TIMESTAMP                ,
       TAB_A.LAST_UPDATE_USER                     ,
       TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01        ,
       TAB_C.ACCESS_AUTH AS ACCESS_AUTH_02        ,
       TAB_D.ACCESS_AUTH AS ACCESS_AUTH_03 
FROM F_CREATE_ITEM_INFO_JNL TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID)
LEFT JOIN G_OTHER_MENU_LINK TAB_C ON (TAB_B.MENU_NAME = TAB_C.MENU_NAME)
LEFT JOIN F_COLUMN_GROUP TAB_D ON (TAB_A.COL_GROUP_ID = TAB_D.COL_GROUP_ID)
WHERE NOT TAB_A.INPUT_METHOD_ID = 7 AND NOT TAB_A.INPUT_METHOD_ID = 11 AND TAB_B.DISUSE_FLAG='0' AND TAB_C.DISUSE_FLAG='0'
;


-- -------------------------
-- パラメータシート(オペレーションあり)参照情報
-- -------------------------
CREATE OR REPLACE VIEW G_CREATE_REFERENCE_SHEET_TYPE_3 AS 
SELECT DISTINCT TAB_A.CREATE_ITEM_ID ITEM_ID      ,
       TAB_B.MENU_NAME MENU_NAME                  ,
       TAB_B.MENUGROUP_FOR_SUBST MENUGROUP_FOR_SUBST ,
       TAB_C.MENU_ID MENU_ID                      ,
       TAB_C.MENU_GROUP_ID MENU_GROUP_ID          ,
       TAB_C.MENU_GROUP_NAME MENU_GROUP_NAME      ,
       TAB_D.MENU_TABLE_LINK_ID MENU_TABLE_LINK_ID,
       TAB_D.TABLE_NAME TABLE_NAME                ,
       TAB_A.CREATE_ITEM_ID CREATE_ITEM_ID        ,
       TAB_A.ITEM_NAME ITEM_NAME                  ,
       TAB_A.INPUT_METHOD_ID INPUT_METHOD_ID      ,
       TAB_E.COL_GROUP_ID COL_GROUP_ID            ,
       TAB_E.FULL_COL_GROUP_NAME FULL_COL_GROUP_NAME ,
       CASE WHEN TAB_E.FULL_COL_GROUP_NAME IS NULL THEN TAB_A.ITEM_NAME ELSE CONCAT(TAB_E.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME) END AS COL_TITLE,
       CASE WHEN TAB_E.FULL_COL_GROUP_NAME IS NULL THEN CONCAT(TAB_C.MENU_GROUP_NAME,':',TAB_B.MENU_NAME,':',TAB_A.ITEM_NAME) ELSE CONCAT(TAB_C.MENU_GROUP_NAME,':',TAB_B.MENU_NAME,':',TAB_E.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME) END AS MENU_PULLDOWN,
       CASE WHEN CHAR_LENGTH(TAB_A.CREATE_ITEM_ID) <= 4 THEN CONCAT('KY_AUTO_COL_', lpad(TAB_A.CREATE_ITEM_ID, 4, '0')) ELSE CONCAT('KY_AUTO_COL_', TAB_A.CREATE_ITEM_ID) END AS COLUMN_NAME,
       TAB_A.DISP_SEQ DISP_SEQ                    ,
       TAB_A.ACCESS_AUTH                          ,
       TAB_A.NOTE                                 ,
       TAB_A.DISUSE_FLAG                          ,
       TAB_A.LAST_UPDATE_TIMESTAMP                ,
       TAB_A.LAST_UPDATE_USER                     ,
       TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01        ,
       TAB_C.ACCESS_AUTH AS ACCESS_AUTH_02        ,
       TAB_D.ACCESS_AUTH AS ACCESS_AUTH_03        ,
       TAB_E.ACCESS_AUTH AS ACCESS_AUTH_04
FROM F_CREATE_ITEM_INFO TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID AND TAB_B.TARGET='3')
LEFT JOIN D_MENU_LIST TAB_C ON (TAB_B.MENU_NAME = TAB_C.MENU_NAME AND TAB_C.MENU_GROUP_ID = TAB_B.MENUGROUP_FOR_SUBST)
LEFT JOIN F_MENU_TABLE_LINK TAB_D ON (TAB_C.MENU_ID = TAB_D.MENU_ID)
LEFT JOIN F_COLUMN_GROUP TAB_E ON (TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID)
WHERE (TAB_A.DISUSE_FLAG='0' AND TAB_B.DISUSE_FLAG='0' AND TAB_C.DISUSE_FLAG='0' AND TAB_D.DISUSE_FLAG='0')
AND (TAB_A.INPUT_METHOD_ID != 7 AND TAB_A.INPUT_METHOD_ID != 11)
;

CREATE OR REPLACE VIEW G_CREATE_REFERENCE_SHEET_TYPE_3_JNL AS 
SELECT DISTINCT TAB_A.JOURNAL_SEQ_NO              ,
       TAB_A.JOURNAL_REG_DATETIME                 ,
       TAB_A.JOURNAL_ACTION_CLASS                 ,
       TAB_A.CREATE_ITEM_ID ITEM_ID               ,
       TAB_B.MENU_NAME MENU_NAME                  ,
       TAB_B.MENUGROUP_FOR_SUBST MENUGROUP_FOR_SUBST ,
       TAB_C.MENU_ID MENU_ID                      ,
       TAB_C.MENU_GROUP_ID MENU_GROUP_ID          ,
       TAB_C.MENU_GROUP_NAME MENU_GROUP_NAME      ,
       TAB_D.MENU_TABLE_LINK_ID MENU_TABLE_LINK_ID,
       TAB_D.TABLE_NAME TABLE_NAME                ,
       TAB_A.CREATE_ITEM_ID CREATE_ITEM_ID        ,
       TAB_A.ITEM_NAME ITEM_NAME                  ,
       TAB_A.INPUT_METHOD_ID INPUT_METHOD_ID      ,
       TAB_E.COL_GROUP_ID COL_GROUP_ID            ,
       TAB_E.FULL_COL_GROUP_NAME FULL_COL_GROUP_NAME ,
       CASE WHEN TAB_E.FULL_COL_GROUP_NAME IS NULL THEN TAB_A.ITEM_NAME ELSE CONCAT(TAB_E.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME) END AS COL_TITLE,
       CASE WHEN TAB_E.FULL_COL_GROUP_NAME IS NULL THEN CONCAT(TAB_C.MENU_GROUP_NAME,':',TAB_B.MENU_NAME,':',TAB_A.ITEM_NAME) ELSE CONCAT(TAB_C.MENU_GROUP_NAME,':',TAB_B.MENU_NAME,':',TAB_E.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME) END AS MENU_PULLDOWN,
       CASE WHEN CHAR_LENGTH(TAB_A.CREATE_ITEM_ID) <= 4 THEN CONCAT('KY_AUTO_COL_', lpad(TAB_A.CREATE_ITEM_ID, 4, '0')) ELSE CONCAT('KY_AUTO_COL_', TAB_A.CREATE_ITEM_ID) END AS COLUMN_NAME,
       TAB_A.DISP_SEQ DISP_SEQ                    ,
       TAB_A.ACCESS_AUTH                          ,
       TAB_A.NOTE                                 ,
       TAB_A.DISUSE_FLAG                          ,
       TAB_A.LAST_UPDATE_TIMESTAMP                ,
       TAB_A.LAST_UPDATE_USER                     ,
       TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01        ,
       TAB_C.ACCESS_AUTH AS ACCESS_AUTH_02        ,
       TAB_D.ACCESS_AUTH AS ACCESS_AUTH_03        ,
       TAB_E.ACCESS_AUTH AS ACCESS_AUTH_04
FROM F_CREATE_ITEM_INFO_JNL TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID AND TAB_B.TARGET='3')
LEFT JOIN D_MENU_LIST TAB_C ON (TAB_B.MENU_NAME = TAB_C.MENU_NAME AND TAB_C.MENU_GROUP_ID = TAB_B.MENUGROUP_FOR_SUBST)
LEFT JOIN F_MENU_TABLE_LINK TAB_D ON (TAB_C.MENU_ID = TAB_D.MENU_ID)
LEFT JOIN F_COLUMN_GROUP TAB_E ON (TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID)
WHERE (TAB_A.DISUSE_FLAG='0' AND TAB_B.DISUSE_FLAG='0' AND TAB_C.DISUSE_FLAG='0' AND TAB_D.DISUSE_FLAG='0')
AND (TAB_A.INPUT_METHOD_ID != 7 AND TAB_A.INPUT_METHOD_ID != 11)
;


INSERT INTO F_INPUT_METHOD (INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(11,'パラメータシート参照',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO F_INPUT_METHOD_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(11,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',11,'パラメータシート参照',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
