ALTER TABLE F_CREATE_MENU_INFO ADD COLUMN VERTICAL INT AFTER TARGET;
ALTER TABLE F_CREATE_MENU_INFO ADD COLUMN MENUGROUP_FOR_INPUT INT AFTER VERTICAL;
ALTER TABLE F_CREATE_MENU_INFO ADD COLUMN MENUGROUP_FOR_SUBST INT AFTER MENUGROUP_FOR_INPUT;
ALTER TABLE F_CREATE_MENU_INFO ADD COLUMN ACCESS_AUTH TEXT AFTER DESCRIPTION;

UPDATE F_CREATE_MENU_INFO SET VERTICAL=1,MENUGROUP_FOR_INPUT=MENUGROUP_FOR_CONV,MENUGROUP_FOR_SUBST=MENUGROUP_FOR_H WHERE MENUGROUP_FOR_CONV IS NOT NULL;
UPDATE F_CREATE_MENU_INFO SET MENUGROUP_FOR_INPUT=MENUGROUP_FOR_HG,MENUGROUP_FOR_SUBST=MENUGROUP_FOR_H WHERE MENUGROUP_FOR_HG  IS NOT NULL AND MENUGROUP_FOR_CONV IS NULL;
UPDATE F_CREATE_MENU_INFO SET MENUGROUP_FOR_INPUT=MENUGROUP_FOR_H WHERE MENUGROUP_FOR_HG IS NULL AND MENUGROUP_FOR_CONV IS NULL;

ALTER TABLE F_CREATE_MENU_INFO DROP COLUMN MENUGROUP_FOR_HG;
ALTER TABLE F_CREATE_MENU_INFO DROP COLUMN MENUGROUP_FOR_H;
ALTER TABLE F_CREATE_MENU_INFO DROP COLUMN MENUGROUP_FOR_CONV;
ALTER TABLE F_CREATE_MENU_INFO DROP COLUMN MENUGROUP_FOR_CMDB;

ALTER TABLE F_CREATE_MENU_INFO_JNL ADD COLUMN VERTICAL INT AFTER TARGET;
ALTER TABLE F_CREATE_MENU_INFO_JNL ADD COLUMN MENUGROUP_FOR_INPUT INT AFTER VERTICAL;
ALTER TABLE F_CREATE_MENU_INFO_JNL ADD COLUMN MENUGROUP_FOR_SUBST INT AFTER MENUGROUP_FOR_INPUT;
ALTER TABLE F_CREATE_MENU_INFO_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DESCRIPTION;

UPDATE F_CREATE_MENU_INFO_JNL SET VERTICAL=1,MENUGROUP_FOR_INPUT=MENUGROUP_FOR_CONV,MENUGROUP_FOR_SUBST=MENUGROUP_FOR_H WHERE MENUGROUP_FOR_CONV IS NOT NULL;
UPDATE F_CREATE_MENU_INFO_JNL SET MENUGROUP_FOR_INPUT=MENUGROUP_FOR_HG,MENUGROUP_FOR_SUBST=MENUGROUP_FOR_H WHERE MENUGROUP_FOR_HG IS NOT NULL AND MENUGROUP_FOR_CONV IS NULL;
UPDATE F_CREATE_MENU_INFO_JNL SET MENUGROUP_FOR_INPUT=MENUGROUP_FOR_H WHERE MENUGROUP_FOR_HG IS NULL AND MENUGROUP_FOR_CONV IS NULL;

ALTER TABLE F_CREATE_MENU_INFO_JNL DROP COLUMN MENUGROUP_FOR_HG;
ALTER TABLE F_CREATE_MENU_INFO_JNL DROP COLUMN MENUGROUP_FOR_H;
ALTER TABLE F_CREATE_MENU_INFO_JNL DROP COLUMN MENUGROUP_FOR_CONV;
ALTER TABLE F_CREATE_MENU_INFO_JNL DROP COLUMN MENUGROUP_FOR_CMDB;

ALTER TABLE F_CREATE_ITEM_INFO MODIFY COLUMN PREG_MATCH TEXT;
ALTER TABLE F_CREATE_ITEM_INFO MODIFY COLUMN PREG_MATCH TEXT;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN PW_MAX_LENGTH INT AFTER FLOAT_DIGIT;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN UPLOAD_MAX_SIZE LONG AFTER PW_MAX_LENGTH;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN LINK_LENGTH INT AFTER UPLOAD_MAX_SIZE;
ALTER TABLE F_CREATE_ITEM_INFO ADD COLUMN ACCESS_AUTH TEXT AFTER DESCRIPTION;

ALTER TABLE F_CREATE_ITEM_INFO_JNL MODIFY COLUMN PREG_MATCH TEXT;
ALTER TABLE F_CREATE_ITEM_INFO_JNL MODIFY COLUMN PREG_MATCH TEXT;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN PW_MAX_LENGTH INT AFTER FLOAT_DIGIT;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN UPLOAD_MAX_SIZE LONG AFTER PW_MAX_LENGTH;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN LINK_LENGTH INT AFTER UPLOAD_MAX_SIZE;
ALTER TABLE F_CREATE_ITEM_INFO_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DESCRIPTION;

ALTER TABLE F_MENU_TABLE_LINK ADD COLUMN ACCESS_AUTH TEXT AFTER TABLE_NAME_JNL;

ALTER TABLE F_MENU_TABLE_LINK_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER TABLE_NAME_JNL;

ALTER TABLE F_CREATE_MENU_STATUS ADD COLUMN ACCESS_AUTH TEXT AFTER FILE_NAME;

ALTER TABLE F_CREATE_MENU_STATUS_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER FILE_NAME;

ALTER TABLE F_CM_STATUS_MASTER ADD COLUMN ACCESS_AUTH TEXT AFTER STATUS_NAME;

ALTER TABLE F_CM_STATUS_MASTER_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER STATUS_NAME;

ALTER TABLE F_PARAM_PURPOSE ADD COLUMN ACCESS_AUTH TEXT AFTER PURPOSE_NAME;

ALTER TABLE F_PARAM_PURPOSE_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER PURPOSE_NAME;

ALTER TABLE F_OTHER_MENU_LINK ADD COLUMN ACCESS_AUTH TEXT AFTER COLUMN_TYPE;

ALTER TABLE F_OTHER_MENU_LINK_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER COLUMN_TYPE;

ALTER TABLE F_INPUT_METHOD ADD COLUMN ACCESS_AUTH TEXT AFTER INPUT_METHOD_NAME;

ALTER TABLE F_INPUT_METHOD_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER INPUT_METHOD_NAME;

ALTER TABLE F_COLUMN_GROUP ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_COLUMN_GROUP_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_CONVERT_PARAM_INFO ADD COLUMN ACCESS_AUTH TEXT AFTER REPEAT_CNT;

ALTER TABLE F_CONVERT_PARAM_INFO_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER REPEAT_CNT;

ALTER TABLE F_COL_TO_ROW_MNG ADD COLUMN ACCESS_AUTH TEXT AFTER CHANGED_FLG;

ALTER TABLE F_COL_TO_ROW_MNG_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER CHANGED_FLG;

DROP TABLE F_CREATE_MST_MENU_INFO;

DROP TABLE F_CREATE_MST_MENU_INFO_JNL;

DROP TABLE F_CREATE_MST_ITEM_INFO_JNL;

DROP TABLE F_MST_MENU_TABLE_LINK_JNL;

DROP TABLE F_MST_TABLE_ITEM_LIST;

DROP TABLE F_MST_TABLE_ITEM_LIST_JNL;

DROP TABLE F_CREATE_MST_MENU_STATUS;

DROP TABLE F_CREATE_MST_MENU_STATUS_JNL;

CREATE OR REPLACE VIEW G_REQUIRED_MASTER AS
SELECT 1      AS REQUIRED_ID            ,
       '●'   AS REQUIRED_NAME          ,
       ''     AS ACCESS_AUTH            ,
       '0'    AS DISUSE_FLAG            ,
       NOW(6) AS LAST_UPDATE_TIMESTAMP  ,
       1      AS LAST_UPDATE_USER
;

CREATE OR REPLACE VIEW G_OTHER_MENU_LINK AS 
SELECT TAB_A.LINK_ID,
       TAB_C.MENU_GROUP_ID,
       TAB_C.MENU_GROUP_NAME,
       TAB_A.MENU_ID,
       TAB_A.MENU_ID MENU_ID_CLONE,
       TAB_B.MENU_NAME,
       TAB_A.COLUMN_DISP_NAME,
       CONCAT(TAB_C.MENU_GROUP_NAME,':',TAB_B.MENU_NAME,':',TAB_A.COLUMN_DISP_NAME) LINK_PULLDOWN,
       TAB_A.TABLE_NAME,
       TAB_A.PRI_NAME,
       TAB_A.COLUMN_NAME,
       TAB_A.COLUMN_TYPE,
       TAB_A.ACCESS_AUTH,
       TAB_A.NOTE,
       TAB_A.DISUSE_FLAG,
       TAB_A.LAST_UPDATE_TIMESTAMP,
       TAB_A.LAST_UPDATE_USER
FROM F_OTHER_MENU_LINK TAB_A
LEFT JOIN A_MENU_LIST TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN A_MENU_GROUP_LIST TAB_C ON (TAB_B.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
WHERE TAB_B.DISUSE_FLAG='0' AND TAB_C.DISUSE_FLAG='0'
;

CREATE OR REPLACE VIEW G_OTHER_MENU_LINK_JNL AS 
SELECT TAB_A.JOURNAL_SEQ_NO,
       TAB_A.JOURNAL_REG_DATETIME,
       TAB_A.JOURNAL_ACTION_CLASS,
       TAB_A.LINK_ID,
       TAB_C.MENU_GROUP_ID,
       TAB_C.MENU_GROUP_NAME,
       TAB_A.MENU_ID,
       TAB_A.MENU_ID MENU_ID_CLONE,
       TAB_B.MENU_NAME,
       TAB_A.COLUMN_DISP_NAME,
       CONCAT(TAB_C.MENU_GROUP_NAME,':',TAB_B.MENU_NAME,':',TAB_A.COLUMN_DISP_NAME) LINK_PULLDOWN,
       TAB_A.TABLE_NAME,
       TAB_A.PRI_NAME,
       TAB_A.COLUMN_NAME,
       TAB_A.COLUMN_TYPE,
       TAB_A.ACCESS_AUTH,
       TAB_A.NOTE,
       TAB_A.DISUSE_FLAG,
       TAB_A.LAST_UPDATE_TIMESTAMP,
       TAB_A.LAST_UPDATE_USER
FROM F_OTHER_MENU_LINK_JNL TAB_A
LEFT JOIN A_MENU_LIST TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN A_MENU_GROUP_LIST TAB_C ON (TAB_B.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
WHERE TAB_B.DISUSE_FLAG='0' AND TAB_C.DISUSE_FLAG='0'
;

CREATE OR REPLACE VIEW G_CREATE_ITEM_INFO AS 
SELECT TAB_A.CREATE_ITEM_ID,
       TAB_A.CREATE_MENU_ID,
       TAB_A.ITEM_NAME,
       TAB_A.DISP_SEQ,
       TAB_A.REQUIRED,
       TAB_A.UNIQUED,
       TAB_A.COL_GROUP_ID,
       TAB_A.INPUT_METHOD_ID,
       TAB_A.MAX_LENGTH,
       TAB_A.MULTI_MAX_LENGTH,
       TAB_A.PREG_MATCH,
       TAB_A.MULTI_PREG_MATCH,
       TAB_A.OTHER_MENU_LINK_ID,
       TAB_A.INT_MAX,
       TAB_A.INT_MIN,
       TAB_A.FLOAT_MAX,
       TAB_A.FLOAT_MIN,
       TAB_A.FLOAT_DIGIT,
       TAB_A.PW_MAX_LENGTH,
       TAB_A.UPLOAD_MAX_SIZE,
       TAB_A.LINK_LENGTH,
       TAB_A.DESCRIPTION,
       TAB_C.FULL_COL_GROUP_NAME,
       CASE
           WHEN TAB_C.FULL_COL_GROUP_NAME IS NULL THEN CONCAT(TAB_B.MENU_NAME,':',TAB_A.ITEM_NAME)
           ELSE CONCAT(TAB_B.MENU_NAME,':',TAB_C.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME)
       END LINK_PULLDOWN,
       TAB_A.ACCESS_AUTH,
       TAB_A.NOTE,
       TAB_A.DISUSE_FLAG,
       TAB_A.LAST_UPDATE_TIMESTAMP,
       TAB_A.LAST_UPDATE_USER
FROM F_CREATE_ITEM_INFO TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID)
LEFT JOIN F_COLUMN_GROUP TAB_C ON (TAB_A.COL_GROUP_ID = TAB_C.COL_GROUP_ID)
WHERE TAB_B.VERTICAL != ""
;

CREATE OR REPLACE VIEW G_CREATE_ITEM_INFO_JNL AS 
SELECT TAB_A.JOURNAL_SEQ_NO,
       TAB_A.JOURNAL_REG_DATETIME,
       TAB_A.JOURNAL_ACTION_CLASS,
       TAB_A.CREATE_ITEM_ID,
       TAB_A.CREATE_MENU_ID,
       TAB_A.ITEM_NAME,
       TAB_A.DISP_SEQ,
       TAB_A.REQUIRED,
       TAB_A.UNIQUED,
       TAB_A.COL_GROUP_ID,
       TAB_A.INPUT_METHOD_ID,
       TAB_A.MAX_LENGTH,
       TAB_A.MULTI_MAX_LENGTH,
       TAB_A.PREG_MATCH,
       TAB_A.MULTI_PREG_MATCH,
       TAB_A.OTHER_MENU_LINK_ID,
       TAB_A.INT_MAX,
       TAB_A.INT_MIN,
       TAB_A.FLOAT_MAX,
       TAB_A.FLOAT_MIN,
       TAB_A.FLOAT_DIGIT,
       TAB_A.PW_MAX_LENGTH,
       TAB_A.UPLOAD_MAX_SIZE,
       TAB_A.LINK_LENGTH,
       TAB_A.DESCRIPTION,
       CASE
           WHEN TAB_C.FULL_COL_GROUP_NAME IS NULL THEN CONCAT(TAB_B.MENU_NAME,':',TAB_A.ITEM_NAME)
           ELSE CONCAT(TAB_B.MENU_NAME,':',TAB_C.FULL_COL_GROUP_NAME,'/',TAB_A.ITEM_NAME)
       END LINK_PULLDOWN,
       TAB_A.ACCESS_AUTH,
       TAB_A.NOTE,
       TAB_A.DISUSE_FLAG,
       TAB_A.LAST_UPDATE_TIMESTAMP,
       TAB_A.LAST_UPDATE_USER
FROM F_CREATE_ITEM_INFO_JNL TAB_A
LEFT JOIN F_CREATE_MENU_INFO TAB_B ON (TAB_A.CREATE_MENU_ID = TAB_B.CREATE_MENU_ID)
LEFT JOIN F_COLUMN_GROUP TAB_C ON (TAB_A.COL_GROUP_ID = TAB_C.COL_GROUP_ID)
WHERE TAB_B.VERTICAL != ""
;



UPDATE A_SEQUENCE SET MENU_ID=2100160001, DISP_SEQ=2100610001, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CREATE_MENU_INFO_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160001, DISP_SEQ=2100610002, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CREATE_MENU_INFO_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100160002, DISP_SEQ=2100610003, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CREATE_ITEM_INFO_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160002, DISP_SEQ=2100610004, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CREATE_ITEM_INFO_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100160005, DISP_SEQ=2100610005, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_MENU_TABLE_LINK_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160005, DISP_SEQ=2100610006, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_MENU_TABLE_LINK_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100160004, DISP_SEQ=2100610007, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CREATE_MENU_STATUS_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160004, DISP_SEQ=2100610008, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CREATE_MENU_STATUS_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100160007, DISP_SEQ=2100610009, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_OTHER_MENU_LINK_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160007, DISP_SEQ=2100610010, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_OTHER_MENU_LINK_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100160008, DISP_SEQ=2100610011, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_COLUMN_GROUP_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160008, DISP_SEQ=2100610012, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_COLUMN_GROUP_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100160009, DISP_SEQ=2100610013, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CONVERT_PARAM_INFO_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160009, DISP_SEQ=2100610014, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CONVERT_PARAM_INFO_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100160010, DISP_SEQ=2100610015, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_COL_TO_ROW_MNG_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100160010, DISP_SEQ=2100610016, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_COL_TO_ROW_MNG_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100690001, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CM_STATUS_MASTER_RIC';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100690002, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_CM_STATUS_MASTER_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100690003, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_PARAM_PURPOSE_RIC';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100690004, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_PARAM_PURPOSE_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100690005, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_INPUT_METHOD_RIC';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100690006, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_INPUT_METHOD_JSQ';

INSERT INTO A_MENU_GROUP_LIST (MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2100011610,'Input','for-input.png',52,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO A_MENU_GROUP_LIST_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(-160010,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',2100011610,'Input','for-input.png',52,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO A_MENU_GROUP_LIST (MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2100011611,'Substitution value','for-subst.png',53,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO A_MENU_GROUP_LIST_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(-160011,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',2100011611,'Substitution value','for-subst.png',53,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO A_MENU_GROUP_LIST (MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2100011612,'Reference','for-view.png',54,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO A_MENU_GROUP_LIST_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(-160012,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',2100011612,'Reference','for-view.png',54,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO A_MENU_GROUP_LIST (MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2100011613,'Vertical conveｒsion',NULL,58,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO A_MENU_GROUP_LIST_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_GROUP_ID,MENU_GROUP_NAME,MENU_GROUP_ICON,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(-160013,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',2100011613,'Vertical conveｒsion',NULL,58,'Create Menu','0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);

INSERT INTO F_INPUT_METHOD (INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(8,'Password',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO F_INPUT_METHOD_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(8,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',8,'Password',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO F_INPUT_METHOD (INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(9,'File upload',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO F_INPUT_METHOD_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(9,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',9,'File upload',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO F_INPUT_METHOD (INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(10,'Link',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO F_INPUT_METHOD_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,INPUT_METHOD_ID,INPUT_METHOD_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(10,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',10,'Link',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
