ALTER TABLE F_HOSTGROUP_LIST ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_HOSTGROUP_LIST_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_HOST_LINK_LIST ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_HOST_LINK_LIST_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_HOST_LINK ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_HOST_LINK_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE F_SPLIT_TARGET ADD COLUMN ACCESS_AUTH TEXT AFTER DIVIDED_FLG;

ALTER TABLE F_SPLIT_TARGET_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DIVIDED_FLG;

CREATE OR REPLACE VIEW G_SPLIT_TARGET AS 
SELECT TAB_A.ROW_ID                 ,
       TAB_B.MENU_GROUP_ID          INPUT_MENU_GROUP_ID,
       TAB_C.MENU_GROUP_NAME        INPUT_MENU_GROUP_NAME,
       TAB_A.INPUT_MENU_ID          ,
       TAB_B.MENU_NAME              INPUT_MENU_NAME,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE,
       TAB_D.MENU_GROUP_ID          OUTPUT_MENU_GROUP_ID,
       TAB_E.MENU_GROUP_NAME        OUTPUT_MENU_GROUP_NAME,
       TAB_A.OUTPUT_MENU_ID         ,
       TAB_D.MENU_NAME              OUTPUT_MENU_NAME,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE,
       TAB_A.DIVIDED_FLG,
       TAB_A.ACCESS_AUTH            ,
       TAB_A.NOTE                   ,
       TAB_A.DISUSE_FLAG            ,
       TAB_A.LAST_UPDATE_TIMESTAMP  ,
       TAB_A.LAST_UPDATE_USER 
FROM F_SPLIT_TARGET TAB_A
LEFT JOIN A_MENU_LIST TAB_B ON (TAB_A.INPUT_MENU_ID = TAB_B.MENU_ID)
LEFT JOIN A_MENU_GROUP_LIST TAB_C ON (TAB_B.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
LEFT JOIN A_MENU_LIST TAB_D ON (TAB_A.OUTPUT_MENU_ID = TAB_D.MENU_ID)
LEFT JOIN A_MENU_GROUP_LIST TAB_E ON (TAB_D.MENU_GROUP_ID = TAB_E.MENU_GROUP_ID)
;

CREATE OR REPLACE VIEW G_SPLIT_TARGET_JNL AS 
SELECT TAB_A.JOURNAL_SEQ_NO         ,
       TAB_A.JOURNAL_REG_DATETIME   ,
       TAB_A.JOURNAL_ACTION_CLASS   ,
       TAB_A.ROW_ID                 ,
       TAB_B.MENU_GROUP_ID          INPUT_MENU_GROUP_ID,
       TAB_C.MENU_GROUP_NAME        INPUT_MENU_GROUP_NAME,
       TAB_A.INPUT_MENU_ID          ,
       TAB_B.MENU_NAME              INPUT_MENU_NAME,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE,
       TAB_D.MENU_GROUP_ID          OUTPUT_MENU_GROUP_ID,
       TAB_E.MENU_GROUP_NAME        OUTPUT_MENU_GROUP_NAME,
       TAB_A.OUTPUT_MENU_ID         ,
       TAB_D.MENU_NAME              OUTPUT_MENU_NAME,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE,
       TAB_A.DIVIDED_FLG,
       TAB_A.ACCESS_AUTH            ,
       TAB_A.NOTE                   ,
       TAB_A.DISUSE_FLAG            ,
       TAB_A.LAST_UPDATE_TIMESTAMP  ,
       TAB_A.LAST_UPDATE_USER 
FROM F_SPLIT_TARGET_JNL TAB_A
LEFT JOIN A_MENU_LIST TAB_B ON (TAB_A.INPUT_MENU_ID = TAB_B.MENU_ID)
LEFT JOIN A_MENU_GROUP_LIST TAB_C ON (TAB_B.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
LEFT JOIN A_MENU_LIST TAB_D ON (TAB_A.OUTPUT_MENU_ID = TAB_D.MENU_ID)
LEFT JOIN A_MENU_GROUP_LIST TAB_E ON (TAB_D.MENU_GROUP_ID = TAB_E.MENU_GROUP_ID)
;
CREATE OR REPLACE VIEW G_UQ_HOST_LIST AS
SELECT SYSTEM_ID                                                    AS KY_KEY   ,
       CONCAT('[H]',HOSTNAME) AS KY_VALUE ,
       0                                                            AS KY_SOURCE,
       9223372036854775807                                          AS STRENGTH ,
       ACCESS_AUTH                                                  AS ACCESS_AUTH,
       DISUSE_FLAG                                                              ,
       LAST_UPDATE_TIMESTAMP                                                    ,
       LAST_UPDATE_USER
FROM   C_STM_LIST
WHERE  DISUSE_FLAG = '0'
UNION
SELECT ROW_ID + 10000                                                       AS KY_KEY   ,
       CONCAT('[HG]',HOSTGROUP_NAME)  AS KY_VALUE ,
       1                                                                    AS KY_SOURCE,
       STRENGTH                                                             AS STRENGTH ,
       ACCESS_AUTH                                                          AS ACCESS_AUTH,
       DISUSE_FLAG                                                                      ,
       LAST_UPDATE_TIMESTAMP                                                            ,
       LAST_UPDATE_USER
FROM   F_HOSTGROUP_LIST
WHERE  DISUSE_FLAG = '0'
;

CREATE OR REPLACE VIEW G_FLAG_MASTER AS
SELECT 1      AS FLAG_ID                ,
       '●'   AS FLAG_NAME              ,
       ''     AS ACCESS_AUTH            ,
       NULL   AS NOTE                   ,
       '0'    AS DISUSE_FLAG            ,
       NOW(6) AS LAST_UPDATE_TIMESTAMP  ,
       1      AS LAST_UPDATE_USER
;



UPDATE A_SEQUENCE SET MENU_ID=2100170001, DISP_SEQ=2100710001, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_HOSTGROUP_LIST_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100170001, DISP_SEQ=2100710002, NOTE='履歴テーブル用', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_HOSTGROUP_LIST_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100170002, DISP_SEQ=2100710003, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_HOST_LINK_LIST_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100170002, DISP_SEQ=2100710004, NOTE='履歴テーブル用', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_HOST_LINK_LIST_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100170003, DISP_SEQ=2100710005, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_HOST_LINK_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100170003, DISP_SEQ=2100710006, NOTE='履歴テーブル用', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_HOST_LINK_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100170004, DISP_SEQ=2100710007, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_SPLIT_TARGET_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100170004, DISP_SEQ=2100710008, NOTE='履歴テーブル用', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='F_SPLIT_TARGET_JSQ';
