ALTER TABLE B_OPENST_DETAIL_STATUS ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE B_OPENST_DETAIL_STATUS_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE B_OPENST_IF_INFO ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE B_OPENST_IF_INFO_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE B_OPENST_PROJECT_INFO ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE B_OPENST_VARS_ASSIGN ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE B_OPENST_VARS_ASSIGN_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE C_OPENST_RESULT_DETAIL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE C_OPENST_RESULT_DETAIL_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE C_OPENST_RESULT_MNG ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

ALTER TABLE C_OPENST_RESULT_MNG_JNL ADD COLUMN ACCESS_AUTH TEXT AFTER DISP_SEQ;

CREATE OR REPLACE VIEW D_OPENST_IF_INFO AS
SELECT
        OPENST_IF_INFO_ID        ,
        OPENST_PROTOCOL          ,
        OPENST_HOSTNAME          ,
        OPENST_PORT              ,
        OPENST_USER              ,
        OPENST_PASSWORD          ,
        OPENST_REFRESH_INTERVAL  ,
        DISP_SEQ                 ,
        ACCESS_AUTH              ,
        NOTE                     ,
        DISUSE_FLAG              ,
        LAST_UPDATE_TIMESTAMP    ,
        LAST_UPDATE_USER
FROM B_OPENST_IF_INFO
;

CREATE OR REPLACE VIEW D_OPENST_IF_INFO_JNL AS
SELECT
        JOURNAL_SEQ_NO           ,
        JOURNAL_REG_DATETIME     ,
        JOURNAL_ACTION_CLASS     ,
        OPENST_IF_INFO_ID        ,
        OPENST_PROTOCOL          ,
        OPENST_HOSTNAME          ,
        OPENST_PORT              ,
        OPENST_USER              ,
        OPENST_PASSWORD          ,
        OPENST_REFRESH_INTERVAL  ,
        DISP_SEQ                 ,
        ACCESS_AUTH              ,
        NOTE                     ,
        DISUSE_FLAG              ,
        LAST_UPDATE_TIMESTAMP    ,
        LAST_UPDATE_USER
FROM B_OPENST_IF_INFO_JNL
;

CREATE OR REPLACE VIEW E_OPENST_PATTERN AS 
SELECT 
        PATTERN_ID                   ,
        PATTERN_NAME                 ,
        CONCAT(PATTERN_ID,':',PATTERN_NAME) PATTERN,
        ITA_EXT_STM_ID               ,
        TIME_LIMIT                   ,
        ANS_HOST_DESIGNATE_TYPE_ID   ,
        ANS_PARALLEL_EXE             ,
        ANS_WINRM_ID                 ,
        OPENST_TEMPLATE              ,
        OPENST_ENVIRONMENT           ,
        DISP_SEQ                     ,
        ACCESS_AUTH                  ,
        NOTE                         ,
        DISUSE_FLAG                  ,
        LAST_UPDATE_TIMESTAMP        ,
        LAST_UPDATE_USER
FROM C_PATTERN_PER_ORCH TAB_A
WHERE TAB_A.ITA_EXT_STM_ID = 9
;

CREATE OR REPLACE VIEW E_OPENST_PATTERN_JNL AS 
SELECT 
        JOURNAL_SEQ_NO               ,
        JOURNAL_REG_DATETIME         ,
        JOURNAL_ACTION_CLASS         ,
        PATTERN_ID                   ,
        PATTERN_NAME                 ,
        CONCAT(PATTERN_ID,':',PATTERN_NAME) PATTERN,
        ITA_EXT_STM_ID               ,
        TIME_LIMIT                   ,
        ANS_HOST_DESIGNATE_TYPE_ID   ,
        ANS_PARALLEL_EXE             ,
        ANS_WINRM_ID                 ,
        OPENST_TEMPLATE              ,
        OPENST_ENVIRONMENT           ,
        DISP_SEQ                     ,
        ACCESS_AUTH                  ,
        NOTE                         ,
        DISUSE_FLAG                  ,
        LAST_UPDATE_TIMESTAMP        ,
        LAST_UPDATE_USER
FROM C_PATTERN_PER_ORCH_JNL TAB_A
WHERE TAB_A.ITA_EXT_STM_ID = 9
;

CREATE OR REPLACE VIEW E_OPENST_RESULT_MNG AS
SELECT
        TAB_A.EXECUTION_NO           ,
        TAB_A.SYMPHONY_NAME          ,
        TAB_A.EXECUTION_USER         ,
        TAB_A.STATUS_ID              ,
        TAB_C.STATUS_NAME            ,
        TAB_A.PATTERN_ID             ,
        TAB_A.I_PATTERN_NAME         ,
        TAB_A.I_TIME_LIMIT           ,
        TAB_A.OPERATION_NO_UAPK      ,
        TAB_A.I_OPERATION_NAME       ,
        TAB_A.I_OPERATION_NO_IDBH    ,
        TAB_A.TIME_BOOK              ,
        TAB_A.TIME_START             ,
        TAB_A.TIME_END               ,
        TAB_A.HEAT_INPUT             ,
        TAB_A.HEAT_RESULT            ,
        TAB_A.RUN_MODE               ,
        TAB_D.RUN_MODE_NAME          ,
        TAB_A.CONDUCTOR_NAME         ,
        TAB_A.CONDUCTOR_INSTANCE_NO  ,
        TAB_A.DISP_SEQ               ,
        TAB_A.ACCESS_AUTH            ,
        TAB_A.NOTE                   ,
        TAB_A.DISUSE_FLAG            ,
        TAB_A.LAST_UPDATE_TIMESTAMP  ,
        TAB_A.LAST_UPDATE_USER
FROM C_OPENST_RESULT_MNG TAB_A
LEFT JOIN E_OPENST_PATTERN TAB_B ON (TAB_B.PATTERN_ID = TAB_A.PATTERN_ID)
LEFT JOIN D_OPENST_STATUS  TAB_C ON (TAB_A.STATUS_ID = TAB_C.STATUS_ID)
LEFT JOIN D_OPENST_LNS_INS_RUN_MODE TAB_D ON (TAB_A.RUN_MODE = TAB_D.RUN_MODE_ID)
;

CREATE OR REPLACE VIEW E_OPENST_RESULT_MNG_JNL AS
SELECT
        TAB_A.JOURNAL_SEQ_NO         ,
        TAB_A.SYMPHONY_NAME          ,
        TAB_A.EXECUTION_USER         ,
        TAB_A.JOURNAL_REG_DATETIME   ,
        TAB_A.JOURNAL_ACTION_CLASS   ,
        TAB_A.EXECUTION_NO           ,
        TAB_A.STATUS_ID              ,
        TAB_C.STATUS_NAME            ,
        TAB_A.PATTERN_ID             ,
        TAB_A.I_PATTERN_NAME         ,
        TAB_A.I_TIME_LIMIT           ,
        TAB_A.OPERATION_NO_UAPK      ,
        TAB_A.I_OPERATION_NAME       ,
        TAB_A.I_OPERATION_NO_IDBH    ,
        TAB_A.TIME_BOOK              ,
        TAB_A.TIME_START             ,
        TAB_A.TIME_END               ,
        TAB_A.HEAT_INPUT             ,
        TAB_A.HEAT_RESULT            ,
        TAB_A.RUN_MODE               ,
        TAB_D.RUN_MODE_NAME          ,
        TAB_A.CONDUCTOR_NAME         ,
        TAB_A.CONDUCTOR_INSTANCE_NO  ,
        TAB_A.DISP_SEQ               ,
        TAB_A.ACCESS_AUTH            ,
        TAB_A.NOTE                   ,
        TAB_A.DISUSE_FLAG            ,
        TAB_A.LAST_UPDATE_TIMESTAMP  ,
        TAB_A.LAST_UPDATE_USER
FROM C_OPENST_RESULT_MNG_JNL TAB_A
LEFT JOIN E_OPENST_PATTERN TAB_B ON (TAB_B.PATTERN_ID = TAB_A.PATTERN_ID)
LEFT JOIN D_OPENST_STATUS TAB_C ON (TAB_A.STATUS_ID = TAB_C.STATUS_ID)
LEFT JOIN D_OPENST_LNS_INS_RUN_MODE TAB_D ON (TAB_A.RUN_MODE = TAB_D.RUN_MODE_ID)
;



UPDATE A_SEQUENCE SET MENU_ID=2100070001, DISP_SEQ=2100410001, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_IF_INFO_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100070001, DISP_SEQ=2100410002, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_IF_INFO_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100070003, DISP_SEQ=2100410003, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_VARS_ASSIGN_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100070003, DISP_SEQ=2100410004, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_VARS_ASSIGN_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100070007, DISP_SEQ=2100410005, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='C_OPENST_RESULT_DETAIL_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100070007, DISP_SEQ=2100410006, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='C_OPENST_RESULT_DETAIL_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=2100070006, DISP_SEQ=2100410007, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='C_OPENST_RESULT_MNG_RIC';
UPDATE A_SEQUENCE SET MENU_ID=2100070006, DISP_SEQ=2100410008, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='C_OPENST_RESULT_MNG_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100490001, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_DETAIL_STATUS_RIC';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100490002, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_DETAIL_STATUS_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100490003, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_RUN_MODE_RIC';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100490004, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_RUN_MODE_JSQ';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100490005, NOTE=NULL, LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_STATUS_RIC';
UPDATE A_SEQUENCE SET MENU_ID=NULL, DISP_SEQ=2100490006, NOTE='for the history table.', LAST_UPDATE_TIMESTAMP=STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f') WHERE NAME='B_OPENST_STATUS_JSQ';
