CREATE OR REPLACE VIEW D_ANS_CMDB_LINK AS 
SELECT DISTINCT
  TAB_A.* ,
  TAB_B.MENU_GROUP_ID,
  TAB_B.MENU_GROUP_ID AS MENU_GROUP_ID_CLONE, 
  TAB_C.MENU_GROUP_NAME ,
  TAB_A.MENU_ID AS MENU_ID_CLONE,
  TAB_A.MENU_ID AS MENU_ID_CLONE_02,
  TAB_B.MENU_NAME,
  TAB_A.COLUMN_LIST_ID AS REST_COLUMN_LIST_ID,
  TAB_D.COL_NAME,
  TAB_D.COL_TITLE,
  TAB_D.COL_CLASS,
  TAB_E.TABLE_NAME
FROM (
        (
          B_ANS_CMDB_LINK TAB_A 
          LEFT JOIN A_MENU_LIST TAB_B ON(TAB_A.MENU_ID = TAB_B.MENU_ID)
        ) 
        LEFT JOIN A_MENU_GROUP_LIST TAB_C ON(TAB_B.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
        LEFT JOIN B_CMDB_MENU_COLUMN TAB_D ON(TAB_A.COLUMN_LIST_ID = TAB_D.COLUMN_LIST_ID)
        LEFT JOIN F_MENU_TABLE_LINK TAB_E ON(TAB_A.MENU_ID = TAB_E.MENU_ID)
    )
;

CREATE OR REPLACE VIEW D_ANS_CMDB_LINK_JNL AS 
SELECT DISTINCT
  TAB_A.* ,
  TAB_B.MENU_GROUP_ID,
  TAB_B.MENU_GROUP_ID AS MENU_GROUP_ID_CLONE, 
  TAB_C.MENU_GROUP_NAME ,
  TAB_A.MENU_ID AS MENU_ID_CLONE,
  TAB_A.MENU_ID AS MENU_ID_CLONE_02,
  TAB_B.MENU_NAME,
  TAB_A.COLUMN_LIST_ID AS REST_COLUMN_LIST_ID,
  TAB_D.COL_NAME,
  TAB_D.COL_TITLE,
  TAB_D.COL_CLASS,
  TAB_E.TABLE_NAME
FROM (
        (
          B_ANS_CMDB_LINK_JNL TAB_A 
          LEFT JOIN A_MENU_LIST TAB_B ON(TAB_A.MENU_ID = TAB_B.MENU_ID)
        ) 
        LEFT JOIN A_MENU_GROUP_LIST TAB_C ON(TAB_B.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
        LEFT JOIN B_CMDB_MENU_COLUMN TAB_D ON(TAB_A.COLUMN_LIST_ID = TAB_D.COLUMN_LIST_ID)
        LEFT JOIN F_MENU_TABLE_LINK TAB_E ON(TAB_A.MENU_ID = TAB_E.MENU_ID)
    )
;


CREATE OR REPLACE VIEW D_CMDB_MENU_COLUMN_SHEET_TYPE_4 AS
SELECT
  TAB_B.*,
  TAB_A.ACCESS_AUTH AS ACCESS_AUTH_01   ,
  TAB_A.ACCESS_AUTH_01 AS ACCESS_AUTH_02,
  TAB_A.ACCESS_AUTH_02 AS ACCESS_AUTH_03
FROM
  D_CMDB_MENU_LIST_SHEET_TYPE_1         TAB_A
  LEFT JOIN B_CMDB_MENU_COLUMN TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
WHERE
  TAB_B.DISUSE_FLAG = '0'
;

CREATE OR REPLACE VIEW D_CMDB_MENU_COLUMN_SHEET_TYPE_4_JNL AS
SELECT
  TAB_B.*,
  TAB_A.ACCESS_AUTH AS ACCESS_AUTH_01   ,
  TAB_A.ACCESS_AUTH_01 AS ACCESS_AUTH_02,
  TAB_A.ACCESS_AUTH_02 AS ACCESS_AUTH_03
FROM
  D_CMDB_MENU_LIST_SHEET_TYPE_1_JNL         TAB_A
  LEFT JOIN B_CMDB_MENU_COLUMN_JNL TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
WHERE
  TAB_B.DISUSE_FLAG = '0'
;


UPDATE A_SEQUENCE SET VALUE=4 WHERE NAME='B_COLLECT_STATUS_RIC';
UPDATE A_SEQUENCE SET VALUE=4 WHERE NAME='B_COLLECT_STATUS_JSQ';


INSERT INTO B_COLLECT_STATUS (COLLECT_STATUS_ID,COLLECT_STATUS_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,'収集済み（通知あり）',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO B_COLLECT_STATUS_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLLECT_STATUS_ID,COLLECT_STATUS_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',2,'収集済み（通知あり）',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO B_COLLECT_STATUS (COLLECT_STATUS_ID,COLLECT_STATUS_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(3,'対象外',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
INSERT INTO B_COLLECT_STATUS_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLLECT_STATUS_ID,COLLECT_STATUS_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(3,STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),'INSERT',3,'対象外',NULL,'0',STR_TO_DATE('2015/04/01 10:00:00.000000','%Y/%m/%d %H:%i:%s.%f'),1);
