CREATE OR REPLACE VIEW G_SPLIT_TARGET AS 
SELECT TAB_A.ROW_ID                 ,
       TAB_A.INPUT_MENU_ID          ,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE_02,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE_03,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE_04,
       TAB_A.OUTPUT_MENU_ID         ,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE_02,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE_03,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE_04,
       TAB_A.DIVIDED_FLG,
       TAB_A.ACCESS_AUTH            ,
       TAB_A.NOTE                   ,
       TAB_A.DISUSE_FLAG            ,
       TAB_A.LAST_UPDATE_TIMESTAMP  ,
       TAB_A.LAST_UPDATE_USER 
FROM F_SPLIT_TARGET TAB_A
;

CREATE OR REPLACE VIEW G_SPLIT_TARGET_JNL AS 
SELECT TAB_A.JOURNAL_SEQ_NO         ,
       TAB_A.JOURNAL_REG_DATETIME   ,
       TAB_A.JOURNAL_ACTION_CLASS   ,
       TAB_A.ROW_ID                 ,
       TAB_A.INPUT_MENU_ID          ,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE_02,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE_03,
       TAB_A.INPUT_MENU_ID          INPUT_MENU_ID_CLONE_04,
       TAB_A.OUTPUT_MENU_ID         ,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE_02,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE_03,
       TAB_A.OUTPUT_MENU_ID         OUTPUT_MENU_ID_CLONE_04,
       TAB_A.DIVIDED_FLG,
       TAB_A.ACCESS_AUTH            ,
       TAB_A.NOTE                   ,
       TAB_A.DISUSE_FLAG            ,
       TAB_A.LAST_UPDATE_TIMESTAMP  ,
       TAB_A.LAST_UPDATE_USER 
FROM F_SPLIT_TARGET_JNL TAB_A
;
