CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_TERRACLI AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME 
WHERE 
    DRIVER_TYPE=3;

CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_TERRACLI_JNL AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME_JNL 
WHERE 
    DRIVER_TYPE=3;

CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_ANS_TERRA AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME 
WHERE 
    DRIVER_TYPE=1 AND DRIVER_TYPE=2;

CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_ANS_TERRA_JNL AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME_JNL 
WHERE 
    DRIVER_TYPE=1 AND DRIVER_TYPE=2;

CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_ANS_TERRACLI AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME 
WHERE 
    DRIVER_TYPE=1 AND DRIVER_TYPE=3;

CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_ANS_TERRACLI_JNL AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME_JNL 
WHERE 
    DRIVER_TYPE=1 AND DRIVER_TYPE=3;

CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_TERRA_TERRACLI AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME 
WHERE 
    DRIVER_TYPE=2 AND DRIVER_TYPE=3;

CREATE OR REPLACE VIEW B_CICD_MATERIAL_TYPE_NAME_TERRA_TERRACLI_JNL AS
SELECT 
    * 
FROM 
    B_CICD_MATERIAL_TYPE_NAME_JNL 
WHERE 
    DRIVER_TYPE=2 AND DRIVER_TYPE=3;

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_TERRACLI AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (11);

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_TERRACLI_JNL AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH_JNL    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER_JNL  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (11);

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_ANS_TERRA AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (3,4,5,10);

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_ANS_TERRA_JNL AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH_JNL    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER_JNL  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (3,4,5,10);

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_ANS_TERRACLI AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (3,4,5,11);

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_ANS_TERRACLI_JNL AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH_JNL    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER_JNL  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (3,4,5,11);

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_TERRA_TERRACLI AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (10,11);

CREATE OR REPLACE VIEW D_CICD_MATL_PATTERN_LIST_TERRA_TERRACLI_JNL AS
SELECT
  TAB_A.*,
  TAB_A.PATTERN_ID                                      MATL_PTN_NAME_PULLKEY,
  CONCAT(TAB_B.ITA_EXT_STM_NAME,':',TAB_A.PATTERN_NAME) MATL_PTN_NAME_PULLDOWN,
  TAB_B.ACCESS_AUTH AS ACCESS_AUTH_01
FROM 
            C_PATTERN_PER_ORCH_JNL    TAB_A
  LEFT JOIN B_ITA_EXT_STM_MASTER_JNL  TAB_B ON (TAB_A.ITA_EXT_STM_ID = TAB_B.ITA_EXT_STM_ID)
WHERE
  TAB_A.DISUSE_FLAG = '0' AND
  TAB_B.DISUSE_FLAG = '0' AND
  TAB_A.ITA_EXT_STM_ID in (10,11);
